# Generated by Django 5.2.15 on 2026-07-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comment_like_savedpost'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='teams.team'),
        ),
    ]
