# Generated by Django 5.2.15 on 2026-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_followers_only',
            field=models.BooleanField(default=False),
        ),
    ]
