# Generated by Django 5.2.15 on 2026-07-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
