# Generated by Django 5.2.15 on 2026-07-12 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teammessage_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='deleted_for_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_team_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
