# Generated by Django 5.2.15 on 2026-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('TEAM_INVITE', 'Team Invite'), ('TEAM_JOIN_REQUEST', 'Team Join Request'), ('FOLLOW_REQUEST', 'Follow Request'), ('FOLLOW_ACCEPT', 'Follow Accept'), ('EVENT_REMINDER', 'Event Reminder'), ('CERTIFICATE_AWARDED', 'Certificate Awarded')], max_length=25),
        ),
    ]
